USE board_cutting_db;

CREATE TABLE IF NOT EXISTS t_cabinet_order_item (
    id                  BIGINT         NOT NULL AUTO_INCREMENT COMMENT '主键',
    order_item_id       BIGINT         NOT NULL COMMENT '关联t_order_item.item_id',
    order_id            BIGINT         NOT NULL COMMENT '冗余t_order.order_id',
    user_id             BIGINT         NOT NULL COMMENT '数据隔离，与t_order_item.user_id一致',
    split_batch_code    VARCHAR(50)    NOT NULL COMMENT '拆单批次编号，如ZG-20260519-001',
    source_board_id     VARCHAR(50)    DEFAULT NULL COMMENT '柜体JSON中的板件id',
    workpiece_code      VARCHAR(50)    DEFAULT NULL COMMENT '工件编号，如ZG-001',
    cabinet_name        VARCHAR(100)   DEFAULT NULL COMMENT '所属柜体名称',
    room                VARCHAR(50)    DEFAULT NULL COMMENT '房间',
    purpose             VARCHAR(100)   DEFAULT NULL COMMENT '用途',
    board_type          VARCHAR(50)    DEFAULT NULL COMMENT '板件类型：side/layer/door/back/top/bottom',
    thickness           INT            DEFAULT NULL COMMENT '厚度(mm)',
    grain_direction     VARCHAR(20)    DEFAULT NULL COMMENT '纹理方向：vertical/horizontal/none',
    design_length       INT            DEFAULT NULL COMMENT '设计长度(mm)',
    design_width        INT            DEFAULT NULL COMMENT '设计宽度(mm)',
    position_x          DOUBLE         DEFAULT NULL COMMENT '3D位置X坐标(mm)',
    position_y          DOUBLE         DEFAULT NULL COMMENT '3D位置Y坐标(mm)',
    position_z          DOUBLE         DEFAULT NULL COMMENT '3D位置Z坐标(mm)',
    edge_banding        JSON           DEFAULT NULL COMMENT '封边对象{left,right,top,bottom:boolean}',
    edge_role           JSON           DEFAULT NULL COMMENT '边的业务语义标注',
    hole_operations     JSON           DEFAULT NULL COMMENT '孔加工信息',
    source_board_json   JSON           DEFAULT NULL COMMENT '当前板件原始JSON快照',
    create_time         DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    UNIQUE INDEX idx_coi_order_item (order_item_id) COMMENT '关联TOrderItem唯一索引',
    INDEX idx_coi_order (order_id) COMMENT '按订单查询索引',
    INDEX idx_coi_batch (user_id, order_id, split_batch_code) COMMENT '拆单批次查询索引',
    INDEX idx_coi_workpiece (workpiece_code) COMMENT '工件编号索引',
    CONSTRAINT fk_coi_order_item FOREIGN KEY (order_item_id) REFERENCES t_order_item(item_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_coi_order FOREIGN KEY (order_id) REFERENCES t_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_coi_user FOREIGN KEY (user_id) REFERENCES t_user(user_id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='柜体拆单辅助表';
